### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by PragmaticNick** [GitHubEngine/NetworkProgramming#1]
- [ ] @mentions, #refs, [links](), **formatting**, and <del>tags</del> supported
- [ ] list syntax required (any unordered or ordered list supported)
- [ ] this is a complete item
- [ ] this is an incomplete item
